/**
 * Topic photos confirmed by looking at each car's contact sheet — NOT derived.
 *
 * The feed carries no labels, and frame position does not predict content:
 * on the 1968 Charger the engine bay is frame 46, on the 1975 C10 it's 60 of
 * 62, and the frame right beside a bay is routinely a closed hood. Every entry
 * below was read off a labelled grid of that car's own photos.
 *
 * `engine: null` means the set genuinely contains no engine photograph. Those
 * rows render without an image rather than substituting something that isn't
 * an engine.
 *
 * Generated by gen-verified.mjs. 22 of 63 vehicles reviewed so far.
 */
export type VerifiedPhotos = { engine: string | null; interior: string | null };

export const VERIFIED_PHOTOS: Record<string, VerifiedPhotos> = {
  // 2020 Jeep Gladiator
  "1C6JJTBG3LL110256": { engine: "https://imagesdl.dealercenter.net/1920/1440/202605-d1888df343c44f07855f02c19add56ff.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202605-423026146f7b40babfe0cdd3458ff098.jpg" },
  // 1975 Chevrolet Caprice Classic
  "1N67H5Y201310": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-41361984053944d6adcbc683825e69ee.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-4e29ad76518d4607b1d829d0889aa673.jpg" },
  // 1953 Chevrolet 3100
  "H53K037522": { engine: "https://imagesdl.dealercenter.net/1920/1440/202605-5a87f9f7c4404f75b2f1c5ad96bef8d9.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202605-83d640a3062348cba573a356d5ba743b.jpg" },
  // 1989 Chevrolet Caprice Classic
  "1G1BU51E6KR129033": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-408386069cc4496bbaaa9b080763466e.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-7a2f3e99397a40019d63d064d56e3dbb.jpg" },
  // 1930 Ford Model A
  "A2157139": { engine: "https://imagesdl.dealercenter.net/1920/1440/202606-5fbe3b4eac174c3095627a04dfc006b7.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202606-49a40585716e4afc90e44acd39e04144.jpg" },
  // 1986 Buick Regal
  "1G4GK4777GP425022": { engine: "https://imagesdl.dealercenter.net/1920/1440/202608-ab9ca1ede6ec44f59de68421651c7535.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202608-61a5f747e9c34869a77ae04975e2069c.jpg" },
  // 1968 Dodge Charger
  "XS29L8B244406": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-38de1fdfced245fc92bd90582117f036.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-df4bf596994940248dc8078538fdb938.jpg" },
  // 1983 Porsche 911 SC
  "WP0EA091XDS170942": { engine: "https://imagesdl.dealercenter.net/1920/1440/202508-e1a5e075a0604c3d935b8e31a0811f90.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202508-39b7292d403347f58dcfc7b3715c393d.jpg" },
  // 1978 Toyota Chinook
  "OR52523": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-231bcedd76a94248a1c3bbab49c2b512.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-396be4386de2460c80398128bbb5d23d.jpg" },
  // 1992 GMC Sonoma Regular Cab
  "1GDCS14W4N0820628": { engine: null, interior: "https://imagesdl.dealercenter.net/1920/1440/202512-88698f310c0e46b7a933bca8c8b5698a.jpg" },
  // 1972 Chevrolet Camaro Z28
  "1Q87L2N139986": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-9bbd5299be1c469f8ea4b02e5456cd23.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-3eae61d229c64251bdc246c99a829ccb.jpg" },
  // 1978 Chevrolet C10 Scottsdale
  "CCU148F416711": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-58f9602adc6e4d21ac43dc099519894a.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-8e701404099140828b4fb7ea9bbc0004.jpg" },
  // 1955 Chevrolet Belair
  "C55S115373": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-3ca1cf7412564f8d980080b3d1205e96.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-9a5d469fb77d4e9e805824d8bbfbb4c2.jpg" },
  // 1990 Ford E150 Vans
  "1FDEE14H4LHA75430": { engine: null, interior: "https://imagesdl.dealercenter.net/1920/1440/202604-dd41e188dbf040cc8c9fc63e99af43ec.jpg" },
  // 1987 Porsche 911
  "WP0EB0918HS170313": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-6076e3e692054b28b2155b79ad6d6c36.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-034344948b734d65879f99eb80d9055b.jpg" },
  // 1967 Chevrolet Camaro
  "123377N216224": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-0e4f706ed0ae438e808126fecc3e9c61.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-af0d12ba05954abd9d86c85ebd161b62.jpg" },
  // 1985 Dodge Ram 150
  "1B7FD14T6FS657438": { engine: "https://imagesdl.dealercenter.net/1920/1440/202603-74c7f2a4f87242cb926ad3e8f719d894.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202603-53f908720795493eb52e376f07c61274.jpg" },
  // 2015 Dodge Challenger
  "2C3CDZBT6FH733479": { engine: "https://imagesdl.dealercenter.net/1920/1440/202605-6d2eb11d9d30414ab60f141258f6a08a.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202605-78229aff02ad488ab5775cce164b8ac0.jpg" },
  // 1975 Chevrolet C10
  "CC0145F412316": { engine: "https://imagesdl.dealercenter.net/1920/1440/202606-b89d98191ac945869de8861633471aba.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202606-d89ae10039db48be97217f3442a65722.jpg" },
  // 1960 Chevrolet Impala
  "01837N176084": { engine: "https://imagesdl.dealercenter.net/1920/1440/202606-fb58270d1b5a4548851a4828b9730e5a.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202606-41d067685b0442f8bacbb9ad07b6b1de.jpg" },
  // 1981 Chevrolet Corvette
  "1G1AY8765BS428829": { engine: "https://imagesdl.dealercenter.net/1920/1440/202606-06f76ec8d28440ec8fa1dab1d56a4b66.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202606-cf2aaae97c0f48f7a3484b6949bace62.jpg" },
  // 1966 Chevrolet Impala S
  "NCS101451": { engine: "https://imagesdl.dealercenter.net/1920/1440/202607-246d32d47f0840fbb5f84aae96e4046f.jpg", interior: "https://imagesdl.dealercenter.net/1920/1440/202607-272cae0039d24127906ab0c4ba12ad7b.jpg" },
};
